stages:
  - build
  - test

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.0"

before_script:
  - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
      - "*/build/outputs/aar/*.aar"

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - "*/build/reports/tests/"