server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{Schema}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: { username }
    password: { password }
  jpa:
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
cloud:
  aws:
    s3:
      bucket: semonemo
    stack.auto: false
    region.static: us-east-1
    credentials:
      accessKey: { accessKey }
      secretKey: { secretKey }


